### ISSUE TITLE
Does it support GPU?

### ISSUE THREAD

**Issue by DerekChia** [Emma926/paradnn#2]
I don't see the instruction to support GPU. Wonder if I can run it on GPU(s)? Thanks.

**Comment by Emma926** [comment]
Yes. You should be able to run paradnn/run/fc_cpu.sh on a machine installed with Tensorflow-GPU. If you want, you can make a copy of paradnn/run/fc_cpu.sh and replace 'cpu' with 'gpu' in it. Let me know if there is any issue!

**Comment by tunghoang290780** [comment]
@Emma926 With @DerekChia question, I looked into fc.py script and did not see how GPU and CPU support are distinguished from each other.  The input argument "use_tpu" is boolean and just meaning that 'TPU' or 'non-TPU'. In detail, both "run_cpu.sh" and "run_gpu.sh" will enable GPUs. We can pass "platform" as the input argument of "fc.py" script then derive the value of "use_tpu".  When the 'platform'=cpu, we can disable all existing GPUs such as "os.environ['CUDA_VISIBLE_DEVICES'] = ''

**Comment by Emma926** [comment]
@tunghoang290780  GPU and CPU support does not have any difference. If you installed Tensorflow with GPU, it will automatically use GPU, because in our experimental settings we did not test CPU-only on GPU machines. Thanks for your suggestion. We will push a patch.
